import { IBM_Plex_Sans } from "next/font/google";
import 'react-phone-number-input/style.css'
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";

import ReactQueryProvider from "./lib/react-query";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.className} antialiased`}>
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
